version: "3.9"

services:
  minio-apoo:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-apoo:/data
    env_file:
      - .minio.env
    command: server --console-address ":9001" /data

volumes:
  minio-apoo:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.126,nolock,soft,rw
      device: ":/mnt/user/Misc/minio-apoo"